components/glasses/GlassForm.tsx
- Closes: #186 
If an glass had no image, the field "GlassImages" is undefined. So the access on that undefined throwes an exception.
=> fix: Glass form was not accessable if the glass had no image

components/cocktails/CocktailRecipeForm.tsx, components/ingredients/IngredientForm.tsx, yarn.lock
- Closes: #187 
- There was a wrong condition in the financial card, which results that the ingredients were not shown
- I had some ingredients with volume = 0 -> so a division by 0 throws a NaN error -> fixed this for future edits by adding a check at the form (not 100 % save, but a fast workaround)
=> fix: Cocktail forms calculation was not shown properly, changed volume validation at ingredients form

components/UploadDropZone.tsx, components/layout/AlertBoundary/index.tsx
- Closes: #192 
By adding a unique identifier to the multiple used component "UploadDropZone" the image gets set corretly
=> fix: Image selector set the wrong when field when creating ingredient/glass/garnish (with image) from the cocktail edit view

components/cocktails/CocktailRecipeCardItem.tsx, components/modals/SearchModal.tsx, migrations/20240405142613_fixed_statistics_on_deletion/migration.sql, pages/workspaces/[workspaceId]/manage/statistics/index.tsx, schema.prisma
- Closes: #215 
Fixed the coresponding issue, by solving the chart bar order to the correct way and some ui issues, see below.
=> fix: Fixed incorrect bar orders at statistics and coresponding ui

components/cocktails/CompactCocktailRecipeInstruction.tsx, components/modals/GlobalModal.tsx
- Closes: #238 
Images can be shown as modal from the bar tenders view
=> fix: Image size on bartender´s view

migrations/20240419083417_added_last_workspace_opened/migration.sql, pages/api/workspaces/[workspaceId]/index.ts, pages/api/workspaces/index.ts, schema.prisma
- Closes: #245 
There was no ordering when you have multiple workspaces. Now its sorted by the last visit.
=> fix: Ordered workspaces by last opened

pages/workspaces/[workspaceId]/index.tsx
- Closes: #267 
Added condition, if the search modal is already opened, it won´t be opened again. Resulting, that you´re able to type capital "F".
=> fix: Capital F not working at SearchModal

components/ingredients/IngredientForm.tsx, pages/api/scraper/ingredient.tsx
- Closes: #<issue id>
I changed the unit conversion from "L" -> "ml" to "L" -> "cl" and added a "cl" selection after the conalco import
=> fix: Wrong unit conversion after conalco import

pages/workspaces/[workspaceId]/search.tsx
- Closes: #357 
When you scrolled down to find a cocktail, the page scrolls now back to the top, when a cocktail gets selected.
=> fix: scroll to top on search page when cocktail gets selected

components/layout/ManageEntityLayout.tsx
- Closes: #361 
When using a tablet, and you want to navigate with the buttons you have to scroll a lot, this issue fixes this by making the headbar sticky.
=> fix: mange xy head bar now sticky to the top

components/AvatarImage.tsx, components/cocktails/CocktailRecipeCardItem.tsx, components/cocktails/CompactCocktailRecipeInstruction.tsx, components/modals/SearchModal.tsx, pages/workspaces/[workspaceId]/search.tsx
- Closes: #338 
When using the search page, the cocktail description gets now displayed. Same as in the search modal.
=> feat: Added cocktail description to cocktail card at search modal and search page

components/cocktails/CocktailRecipeForm.tsx, components/garnishes/GarnishForm.tsx, components/glasses/GlassForm.tsx, components/ingredients/IngredientForm.tsx, components/modals/GlobalModal.tsx, lib/context/ModalContextProvider.tsx, package.json, pages/_app.tsx
- Closes: #334 
Changed the modal method from checkbox (depr.) to the latest way to dialog tags. This resolves the issue, that the modal closes when hitting the backpane of the modal.
Added addititionally an modal stack. This prevents the modal from closing when opening another modal from within.
=> fix: Fixed closing modal bug in chrome/-ium and safari and added stackable modals

package.json, pages/index.tsx, pnpm-lock.yaml, prisma/migrations/20240812120204_notify_new_version/migration.sql, prisma/schema.prisma
- Closes: #170 
Until now it was not really shown, that a new version was relesed. This PR solves this by showing a popup once after a new release was published. Therefor each user has a custom setting property with the last version he saw.
=> feat: 'new version' popup at workspace selection page after new release

pages/workspaces/[workspaceId]/manage/statistics/index.tsx, styles/global.css, tailwind.config.js
When entering 0 to the statistic page date selection, the parsing failed some times.
=> fix: Statistic date input behavior

components/cocktails/CocktailRecipeForm.tsx, components/ingredients/IngredientForm.tsx, pages/api/workspaces/[workspaceId]/calculations/index.tsx, pages/workspaces/[workspaceId]/manage/calculations/[id].tsx, pages/workspaces/[workspaceId]/manage/index.tsx, pages/workspaces/[workspaceId]/manage/ingredients/index.tsx, prisma/migrations/20240826113333_fixed_calculation_constraint/migration.sql, prisma/schema.prisma
When saving an calculation for the first time, an error was thrown (wrong db query). Thats now solved.
If only one unit is available, this one gets preselected at the calculation shopping list unit.
=> fix: Calculation creation and deletion errors solved, set shopping unit preselection if only one is available 

components/cards/CardOverviewItem.tsx, components/cocktails/CocktailRecipeForm.tsx, components/garnishes/GarnishForm.tsx, components/glasses/GlassForm.tsx, components/ingredients/IngredientForm.tsx, components/layout/ManageEntityLayout.tsx, lib/RouterUtils.ts, pages/workspaces/[workspaceId]/manage/calculations/[id].tsx, pages/workspaces/[workspaceId]/manage/cards/[id].tsx, pages/workspaces/[workspaceId]/manage/index.tsx, styles/global.css, tailwind.config.js
- Closes: #423 
I changed the general handling how to go back after editing an entity. The whole navigation should work now better.
- all
=> fix: invalid redirects after saving and on navigation

components/cocktails/CocktailRecipeCardItem.tsx, components/modals/CocktailDetailModal.tsx, lib/network/cocktailRatings.ts, lib/network/cocktails.ts, models/CocktailCardFull.tsx, next.config.js, pages/api/workspaces/[workspaceId]/cards/[cardId]/index.tsx, pages/api/workspaces/[workspaceId]/cards/index.tsx, pages/api/workspaces/[workspaceId]/cocktails/[cocktailId]/index.tsx, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/manage/cards/[id].tsx, pages/workspaces/[workspaceId]/manage/cocktails/[id].tsx
As mentioned in #406 it would be better to fetch each cocktail itself to cache them easily.
Changed the cocktail card item to fetch the cocktail instead of loading all cocktails during the card loading.
- Each card loads the cocktail itself
- Cocktail Detail Modals fetches Ratings independent
- Cocktail card works withouth loading and shows form changes
=> fix: Cocktail recipe card loading behavior improved 

components/cocktails/CocktailRecipeCardItem.tsx, components/cocktails/CompactCocktailRecipeInstruction.tsx, components/cocktails/ShowCocktailInfoButton.tsx, components/modals/CocktailDetailModal.tsx, components/modals/CocktailRatingsModal.tsx, pages/api/auth/[...nextauth].ts, pages/workspaces/[workspaceId]/index.tsx, prisma/migrations/20240915114604_added_cocktail_card_rating_setting/migration.sql, prisma/schema.prisma
Cocktail cards have now ratings aswell, and they also refreshes on update
=> fix: Cocktail card rating option

components/ExpandableText.tsx, components/cocktails/CocktailRecipeCardItem.tsx, pages/workspaces/[workspaceId]/index.tsx
- Closes: #498 
By having long notes, descriptions or history texts, the layout got destroyed pretty fast. To prevent this, i clamped the texts to a maximum of 3 lines and added a show more button. The buttons should only appear if the text is too long. When the layout changes (eye-> layout -> less cols toggle) the clamp gets recalculated.
=> fix: Made long notes, history, and description fields collapsible

package.json, pages/api/workspaces/[workspaceId]/statistics/cocktails/index.tsx, pages/workspaces/[workspaceId]/manage/statistics/index.tsx, pnpm-lock.yaml
- Closes: #526 
When selecting a range longer than 1 day at the statistics, you are now able to group the cocktails by the whole day. I also changed the cocktail day from 0:00-0:00 to 8:00-8:00
=> feat: Added 'group by day' option in statistics

components/StatisticActions.tsx, components/modals/AddCocktailToQueueModal.tsx, components/modals/CocktailDetailModal.tsx, pages/workspaces/[workspaceId]/index.tsx
- Closes: #515
Its now possible to adjust the amount of the cocktail in percentage, changing the ingreident amounts. When changing the default amount, the "add to list with note" gets prefilled with the new amounts as comment.
=> feat: Added cocktail amount adjustment in detail modal

.idea/vcs.xml, pages/workspaces/[workspaceId]/index.tsx, prisma/migrations/20250131114341_queue_ordering/migration.sql, prisma/schema.prisma
- Closes: #533 
Cocktail page -> Eye -> Queue Settings -> Grouping of the queue is now adjustable
=> fix: made cocktail queue grouping/ordering adjustable

pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/search.tsx
None
A design change that you may or may not like:
To make the interface friendlier for touch devices, I increased the size of the queue items (Date and hint about multiple occurrences on an extra line) and bound a click event on the complete queue item, that shows the cocktail details.
When on the search page, the click action instead shows the cocktail details as the cocktail would have been selected via the search.
[Video](https://i.imgur.com/CWlbyOC.mp4)
Nice project!
=> fix: Improved the "view cocktail" from the queue behavior 

components/StatisticActions.tsx, components/cocktails/CocktailRecipeCardItem.tsx, components/layout/AlertBoundary/AlertsContainer.tsx, components/layout/AlertBoundary/index.tsx, components/modals/SearchModal.tsx, components/modals/SelectSpecifyCocktailForStatisticModal.tsx, pages/api/workspaces/[workspaceId]/statistics/cocktails/add.ts, pages/workspaces/[workspaceId]/index.tsx, pages/workspaces/[workspaceId]/search.tsx, prisma/migrations/20250309093018_show_settings_at_bottom/migration.sql, prisma/schema.prisma
This PR makes some small adjustments to improve the experience on small tablet devices (around 9"):
- Add new settings option to show the settings buttons on the bottom of the page instead of letting them float
- Open the cocktail details dialog when clicking on the name/recipe instead of the small info button
- If you do not like this change, this could be made optional
- Increase width of queue-view on lg-sized displays
- Show alerts on the bottom left to not block relevant information, only show alerts for 3 seconds
- Directly mark cocktail as done if there are not cocktails with notes in the queue
- Close cocktail detail dialog after all cocktails of a type has been marked as done.
A release after merging would be appreciated.
=> fix: improve behaviour on mobile/tablet devices

components/CropComponent.tsx, components/ingredients/IngredientForm.tsx
- Closes: #580
- As described in the issue, i added the ingredient volume automaticaly (cl preffered, otherwise, the first unit)
- I changed the crop to have a default crop selection with max size
@ibot3 as you mentioned it would be nice to have the image cropped by default. I didn´t get it to work with the refs so far, so i hope the default crop selection will improve the ux at least a bit. After my thesis end in June i have more time to have look on it.
=> feat: Default crop image and add unit when importing an ingredient from a website
