jo-gross/Cocktail-Manager

components/ListSearchField.tsx

- Closes: #190 
Fixed the method how an icon is displayed at the search components

fix: Fixed chrome ui bug (icon was not correctly displayed)

---

components/ManageColumn.tsx
components/cocktails/CocktailRecipeForm.tsx
components/garnishes/GarnishForm.tsx
components/glasses/GlassForm.tsx
components/ingredients/IngredientForm.tsx
components/modals/DeleteConfirmationModal.tsx
components/modals/NotSavedConfirmation.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
pages/workspaces/[workspaceId]/manage/cards/[id].tsx
pages/workspaces/[workspaceId]/manage/settings/index.tsx

- Closes: #193 
Checked and fixed all loading spinners to the latest handling way

fix: Fixed incomplete loading ui behavior

---

components/cocktails/CocktailRecipeForm.tsx

fix: Broken mobile layout at cocktail form

---

components/cocktails/CocktailRecipeForm.tsx
components/garnishes/GarnishForm.tsx
components/ingredients/IngredientForm.tsx

- Closes: #252 
Fixed the undefined error when creating an ingredient from the cocktail form

fix: Internal error when creating an ingredient from the cocktail form

---

package.json
pages/api/workspaces/[workspaceId]/calculations/[calculationId].tsx
pages/api/workspaces/[workspaceId]/calculations/index.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
schema.prisma
yarn.lock

- Closes: #259 
- Shopping list csv export
- Tick option to mark ingredients as ordred or in stock or what ever you like to

feat: Calculations shopping list got more functions 

---

pages/api/auth/[...nextauth].ts

fix: Login timeout increased

---

docker-compose.yaml

chore: Added local postgres backup strategy to docker-compose file

---

components/modals/CocktailDetailModal.tsx
lib/network/cocktailTracking.ts
pages/workspaces/[workspaceId]/index.tsx
pages/workspaces/[workspaceId]/search.tsx
prisma/migrations/20240620141657_cocktail_queue_overlay/migration.sql
prisma/schema.prisma
styles/global.css

- Closes: #310, #305 
It is now optional to use the queue as overlay. Fixed layout stuff and added sorting to the queue.

fix: Queue overlay layout fixes and made the overlay mode optional

---

styles/global.css

- Closes: #313 
A modal is now below the alert container
- all sites

fix: Alert container now above modals

---

pages/workspaces/[workspaceId]/manage/cards/[id].tsx
pages/workspaces/[workspaceId]/manage/cocktails/[id].tsx
pages/workspaces/[workspaceId]/manage/garnishes/[id].tsx
pages/workspaces/[workspaceId]/manage/glasses/[id].tsx
pages/workspaces/[workspaceId]/manage/ingredients/[id].tsx

- Closes: #347 
Fixed the loading circle to the center on every edit page

fix: Loading ui bug

---

pages/workspaces/[workspaceId]/manage/settings/index.tsx

- Closes: #359
When beeing a manager it was shown that you can remove others, which is not able. Instead of removing others you left the current workspace.

fix: user leave and remove buttons

---

components/cocktails/CompactCocktailRecipeInstruction.tsx
components/modals/ImageModal.tsx
pages/workspaces/[workspaceId]/manage/cocktails/index.tsx
pages/workspaces/[workspaceId]/manage/garnishes/index.tsx
pages/workspaces/[workspaceId]/manage/glasses/index.tsx
pages/workspaces/[workspaceId]/manage/ingredients/index.tsx

- Closes: #360 
Made all preview images inspectable.

fix: manage xy made image inspectable

---

components/cocktails/CocktailRecipeForm.tsx

fix: Small ui stuff at cocktail form (glass sorting, garnish opt label, ...)

---

pages/workspaces/[workspaceId]/index.tsx

- Closes: #358 
Made the dropdown scrollable when it´s getting larger than the screen.

fix: View settings dropdown on main page is now scrollable

---

Dockerfile
next.config.js
package.json
pnpm-lock.yaml
styles/global.css

- Closes: ##388
Hopefully some day this bug gets resolved as unexpected as it came...

chore: re-enable webpack minimization

---

pages/api/workspaces/[workspaceId]/cards/[cardId]/clone.tsx
pages/api/workspaces/[workspaceId]/cards/[cardId]/index.tsx
pages/api/workspaces/[workspaceId]/cards/index.tsx
pages/workspaces/[workspaceId]/index.tsx
pages/workspaces/[workspaceId]/manage/cards/[id].tsx
prisma/migrations/20240912101536_moved_card_time_setting_to_user_setting/migration.sql
prisma/schema.prisma

Cocktail card option "showTime" moved to user specific setting. Restructured the view option layout.

fix: Changed card time option to user specific setting

---

components/CropComponent.tsx
components/cocktails/CocktailRecipeForm.tsx
components/garnishes/GarnishForm.tsx
components/glasses/GlassForm.tsx
components/ingredients/IngredientForm.tsx
lib/ImageCompressor.ts
next-env.d.ts
package.json
pages/workspaces/[workspaceId]/manage/settings/index.tsx
pnpm-lock.yaml

- Closes: #455 
To compress the image and the payload an browser compression extension was used. This caused performance issues on mobile devices. I repaced this with an resize method, which looks way more efficent.

fix: Crop image behavior

---

components/layout/AlertBoundary/index.tsx
pages/api/workspaces/[workspaceId]/queue/index.tsx
pages/api/workspaces/[workspaceId]/queue/remove.ts
pages/workspaces/[workspaceId]/index.tsx

- Closes: #451 
I´ve tried many different order approches, but non worked really well. So i decided to add a timestamp to help the bartender within the decission of the next / oldest one.

fix: Queue order improvement

---

components/cocktails/CompactCocktailRecipeInstruction.tsx
components/garnishes/GarnishForm.tsx
components/modals/CocktailDetailModal.tsx
components/modals/GlobalModal.tsx
pages/_app.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
tailwind.config.js

- Closes: #427 
- Changed the wording from deko to garnish.
- Added option to export cocktail recipe as pdf by printing the page and optimised the view.
- Restructured the garnish descriptions in the cocktail detail modal

feat: Export cocktail as PDF

---

components/cocktails/CocktailRecipeForm.tsx
components/cocktails/CompactCocktailRecipeInstruction.tsx
components/ingredients/IngredientForm.tsx
components/modals/CocktailDetailModal.tsx
components/modals/CocktailRatingsModal.tsx
pages/workspaces/[workspaceId]/index.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
pages/workspaces/[workspaceId]/manage/cocktails/index.tsx
pages/workspaces/[workspaceId]/manage/garnishes/index.tsx
pages/workspaces/[workspaceId]/manage/glasses/index.tsx
pages/workspaces/[workspaceId]/manage/ingredients/index.tsx
pages/workspaces/[workspaceId]/manage/settings/index.tsx

- Closes: #509
- All numbers have now the users localization (in germany commas instead of dots)
- layout of the cocktail queue fixed on mobile devices (now it should look better than before)

fix: Fixed number localization and cocktail queue mobile layout

---

components/ManageColumn.tsx
components/cocktails/CocktailRecipeForm.tsx
components/modals/CocktailRatingsModal.tsx
components/modals/DeleteConfirmationModal.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
pages/workspaces/[workspaceId]/manage/calculations/index.tsx
pages/workspaces/[workspaceId]/manage/cards/[id].tsx
pages/workspaces/[workspaceId]/manage/cocktails/index.tsx
pages/workspaces/[workspaceId]/manage/garnishes/index.tsx
pages/workspaces/[workspaceId]/manage/glasses/index.tsx
pages/workspaces/[workspaceId]/manage/ingredients/index.tsx
pages/workspaces/[workspaceId]/manage/settings/index.tsx

- Closes: #513 
All entities are now named in the delete confirmation dialog

fix: Named all entities in the delete confirmation dialog

---

components/cocktails/CocktailRecipeForm.tsx

- Closes: #502 
I added some tag suggestions in the cocktail form based on the ingredient tags

feat: Added cocktail´s tag suggestion based on the ingredient tags

---

components/modals/AddWorkspaceJoinCodeModal.tsx
pages/workspaces/[workspaceId]/manage/index.tsx
pages/workspaces/[workspaceId]/manage/settings/index.tsx
pages/workspaces/[workspaceId]/manage/settings/users.tsx

fix: Moved user settings to separate page

---

components/StatisticActions.tsx
components/ingredients/IngredientForm.tsx
components/layout/SingleFormLayout.tsx
pages/workspaces/[workspaceId]/manage/index.tsx

- Closes: #525 
Fixed form layouts for mobile, tablet and pc screens

fix: Layout fixes for ingredient, garnish and glass form

---

components/modals/GlobalModal.tsx
components/modals/SearchModal.tsx
pages/workspaces/[workspaceId]/manage/calculations/[id].tsx
pages/workspaces/[workspaceId]/manage/statistics/index.tsx

fix: Calculation "unsaved changes" validation, number formating

---

components/ImportPhotoByUrlModal.tsx
components/UploadDropZone.tsx
components/garnishes/GarnishForm.tsx
components/glasses/GlassForm.tsx
components/ingredients/IngredientForm.tsx
pages/api/scraper/image.tsx
pages/workspaces/[workspaceId]/manage/index.tsx
pages/workspaces/[workspaceId]/manage/monitor/index.tsx
pages/workspaces/[workspaceId]/manage/settings/index.tsx

- Closes: #542
- It´s now possible to import images by an url.
- Restructured the manage menu, changed layout, moved monitor settings to a seperate page

feat: Added option to import images by url and restructured the manage menu

---

components/cocktails/CocktailRecipeForm.tsx

- Closes: #579
If "cl" is available it select it preferred one, otherwise the default selected unit is the first one.

feat: Automatically select first unit when selecting an ingredient 

---

.github/workflows/build-staging-docker.yaml

- Closes: #661 
On every push to main, at 3am and on trigger, a staging build will be released

chore: added staging docker build
